<%@ page import="com.fabricnavigator.security.EdmSecurity,com.fabricnavigator.security.AuditLog,java.io.*,java.nio.file.*,java.util.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private static String h(String value){if(value==null)return "";return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private static File settingsFile(){return new File(System.getProperty("fabricnavigator.data.dir","/opt/fabricnavigator/data"),"openapi.properties");}
private static Properties readSettings(){Properties values=new Properties();File file=settingsFile();if(file.isFile())try(InputStream input=new FileInputStream(file)){values.load(input);}catch(Exception ignored){}return values;}
private static boolean preferred(){return !"false".equalsIgnoreCase(readSettings().getProperty("preferred","true"));}
private static void save(boolean preferred)throws Exception{Properties values=new Properties();values.setProperty("preferred",Boolean.toString(preferred));File file=settingsFile();file.getParentFile().mkdirs();File temporary=File.createTempFile("openapi-",".tmp",file.getParentFile());try{try(Writer writer=new OutputStreamWriter(new FileOutputStream(temporary),"UTF-8")){values.store(writer,"FabricNavigator OpenAPI settings");}try{Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ex){Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING);}}finally{temporary.delete();}}
%>
<%
response.setHeader("Cache-Control","no-store");
if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}
String csrf=EdmSecurity.csrf(session),flash="",error="";
if("POST".equalsIgnoreCase(request.getMethod())){
 if(!EdmSecurity.validCsrf(request)){response.sendError(403);return;}
 try{boolean value="true".equals(request.getParameter("preferOpenApi"));save(value);AuditLog.log(EdmSecurity.currentUser(request),"OPENAPI_PREFERENCE_CHANGED","preferred="+value,com.fabricnavigator.web.ClientAddress.of(request));flash="saved";}catch(Exception ex){error="saveFailed";}
}
boolean preferOpenApi=preferred();
%>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Device API</title><script>(function(){try{document.documentElement.lang=parent.document.documentElement.lang||'de';document.documentElement.setAttribute('data-theme',parent.document.documentElement.getAttribute('data-theme')||'light');}catch(e){}})();</script><link rel="stylesheet" href="/assets/security.css"><style>
html,body{background:transparent!important}body{margin:0;padding:2px;color:var(--fn-text)}.card{padding:22px;border:1px solid var(--fn-border);border-top:4px solid var(--fn-accent);border-radius:14px;background:var(--fn-panel);color:var(--fn-text);box-shadow:var(--fn-shadow)}.card h2{margin:0 0 10px;font-size:19px}.description{padding:12px;border:1px solid color-mix(in srgb,var(--fn-accent) 62%,var(--fn-border));border-left:4px solid var(--fn-accent);border-radius:10px;background:color-mix(in srgb,var(--fn-accent) 10%,var(--fn-panel));color:var(--fn-text);line-height:1.5}.choice{display:flex;align-items:center;gap:10px;margin:18px 0;padding:13px;border:1px solid var(--fn-border);border-radius:10px;background:color-mix(in srgb,var(--fn-accent) 5%,var(--fn-panel));font-weight:800}.choice input{width:18px;height:18px;accent-color:var(--fn-accent)}.alert{padding:12px;border-radius:9px;margin-bottom:14px}.success{background:#e8f8ee;color:#176b36}.error{background:#fdecec;color:#8d1f25}
</style></head><body>
<%if(flash.length()>0){%><div class="alert success" data-de="Die Geräte-API-Einstellung wurde gespeichert." data-en="The Device API preference was saved."></div><%}if(error.length()>0){%><div class="alert error" data-de="Die Geräte-API-Einstellung konnte nicht gespeichert werden." data-en="The Device API preference could not be saved."></div><%}%>
<section class="card"><h2 data-de="Geräte-API" data-en="Device API">Geräte-API</h2><p class="description" data-de="FabricNavigator verwendet OpenAPI zuerst für unterstützte Fabric-Engine-Abfragen. Ist die API nicht verfügbar oder wird ein Vorgang nicht unterstützt, wird automatisch der geprüfte SSH-Fallback verwendet." data-en="FabricNavigator uses OpenAPI first for supported Fabric Engine requests. When the API is unavailable or an operation is unsupported, the verified SSH fallback is used automatically.">FabricNavigator verwendet OpenAPI bevorzugt und fällt bei Bedarf auf SSH zurück.</p><form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><label class="choice"><input type="checkbox" name="preferOpenApi" value="true" <%=preferOpenApi?"checked":""%>><span data-de="OpenAPI primär verwenden" data-en="Prefer OpenAPI">OpenAPI primär verwenden</span></label><button type="submit" data-de="Geräte-API speichern" data-en="Save Device API">Geräte-API speichern</button></form></section>
<script>(function(){var lang=(document.documentElement.lang||'de').indexOf('de')===0?'de':'en';document.querySelectorAll('[data-de][data-en]').forEach(function(node){node.textContent=node.getAttribute('data-'+lang);});}());</script></body></html>
