<%@ page import="com.fabricnavigator.security.EdmSecurity,com.fabricnavigator.security.AuditLog,java.io.*,java.nio.file.*,java.util.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private static String h(String value){if(value==null)return "";return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private static File settingsFile(){return new File(System.getProperty("fabricnavigator.data.dir","/opt/fabricnavigator/data"),"session.properties");}
private static int readTimeout(){Properties p=new Properties();File file=settingsFile();if(file.isFile())try(InputStream in=new FileInputStream(file)){p.load(in);}catch(Exception ignored){}try{return Math.max(5,Math.min(1440,Integer.parseInt(p.getProperty("timeoutMinutes","30").trim())));}catch(Exception ignored){return 30;}}
private static void saveTimeout(int minutes)throws Exception{File file=settingsFile();file.getParentFile().mkdirs();Properties p=new Properties();p.setProperty("timeoutMinutes",Integer.toString(minutes));File temporary=File.createTempFile("session-",".tmp",file.getParentFile());try{try(OutputStream out=new FileOutputStream(temporary)){p.store(out,"FabricNavigator web session settings");}try{Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ex){Files.move(temporary.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING);}}finally{temporary.delete();}}
%>
<%
response.setHeader("Cache-Control","no-store");if(!EdmSecurity.isAdmin(request)){response.sendError(403);return;}
String csrf=EdmSecurity.csrf(session),flash="",error="";int timeout=readTimeout();
if("POST".equalsIgnoreCase(request.getMethod())){if(!EdmSecurity.validCsrf(request)){response.sendError(403);return;}try{int next=Integer.parseInt(request.getParameter("timeoutMinutes"));if(next<5||next>1440)throw new IllegalArgumentException();int previous=timeout;saveTimeout(next);session.setMaxInactiveInterval(next*60);timeout=next;AuditLog.log(EdmSecurity.currentUser(request),"WEB_SESSION_TIMEOUT_CHANGED","old="+previous+" minutes · new="+next+" minutes",com.fabricnavigator.web.ClientAddress.of(request));flash="saved";}catch(Exception ex){error="invalid";}}
%>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Web session</title><script>(function(){try{document.documentElement.lang=parent.document.documentElement.lang||'de';document.documentElement.setAttribute('data-theme',parent.document.documentElement.getAttribute('data-theme')||'light');}catch(e){}})();</script><link rel="stylesheet" href="/assets/security.css"><style>
html,body{background:transparent!important}body{margin:0;padding:2px;color:var(--fn-text)}.card{padding:22px;border:1px solid var(--fn-border);border-top:4px solid var(--fn-accent);border-radius:14px;background:var(--fn-panel);color:var(--fn-text);box-shadow:var(--fn-shadow)}.card h2{margin:0 0 10px;font-size:19px}.description{padding:12px;border:1px solid color-mix(in srgb,var(--fn-accent) 62%,var(--fn-border));border-left:4px solid var(--fn-accent);border-radius:10px;background:color-mix(in srgb,var(--fn-accent) 10%,var(--fn-panel));color:var(--fn-text);line-height:1.5}.field{display:grid;gap:7px;max-width:420px;margin:18px 0;font-weight:800}.field input{min-height:42px;padding:9px 12px;border:1px solid var(--fn-border);border-radius:9px;background:var(--fn-panel);color:var(--fn-text);font:inherit}.hint{color:var(--fn-muted);font-size:12px}.alert{padding:12px;border-radius:9px;margin-bottom:14px}.success{background:#e8f8ee;color:#176b36}.error{background:#fdecec;color:#8d1f25}
</style></head><body>
<%if(flash.length()>0){%><div class="alert success" data-de="Der Web-Sitzungs-Timeout wurde gespeichert." data-en="The web session timeout was saved."></div><%}if(error.length()>0){%><div class="alert error" data-de="Gib einen Wert zwischen 5 und 1440 Minuten ein." data-en="Enter a value between 5 and 1440 minutes."></div><%}%>
<section class="card"><h2 data-de="Web-Sitzung" data-en="Web session">Web-Sitzung</h2><p class="description" data-de="Legt fest, nach wie vielen Minuten ohne Aktivität eine angemeldete Web-Sitzung automatisch beendet wird. Die neue Einstellung gilt sofort für diese Sitzung und bei der nächsten Anfrage für alle anderen Sitzungen." data-en="Defines after how many inactive minutes an authenticated web session ends automatically. The new setting applies immediately to this session and on the next request to all other sessions."></p><form method="post"><input type="hidden" name="csrfToken" value="<%=h(csrf)%>"><label class="field"><span data-de="Timeout in Minuten" data-en="Timeout in minutes">Timeout in Minuten</span><input type="number" name="timeoutMinutes" min="5" max="1440" step="1" value="<%=timeout%>" required><small class="hint" data-de="Erlaubt: 5 bis 1440 Minuten" data-en="Allowed: 5 to 1440 minutes">Erlaubt: 5 bis 1440 Minuten</small></label><button type="submit" data-de="Timeout speichern" data-en="Save timeout">Timeout speichern</button></form></section>
<script>(function(){var lang=(document.documentElement.lang||'de').indexOf('de')===0?'de':'en';document.querySelectorAll('[data-de][data-en]').forEach(function(node){node.textContent=node.getAttribute('data-'+lang);});}());</script></body></html>
