<%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" session="false" %>
<%@ page import="java.util.*,java.util.concurrent.*,java.util.regex.*,java.time.Instant,com.fabricnavigator.api.FabricNavigatorApiToken,com.fabricnavigator.security.AuditLog,com.fabricnavigator.security.CredentialVault,com.fabricnavigator.snmp.SnmpUtilV3" %><%!
private static final long METADATA_TTL_MS=300000L;
private static final Map<String,CachedMetadata> METADATA_CACHE=new ConcurrentHashMap<String,CachedMetadata>();
private static final Pattern VERSION_LABEL=Pattern.compile("(?i)(?:software(?:\\s+version)?|sw(?:\\s+version)?|version|release)\\s*[:=/ -]*([A-Za-z0-9._()-]+)");
private static final Pattern PAREN_VERSION=Pattern.compile("\\(([^()]*(?:\\d+\\.)+\\d+[^()]*)\\)");
private static final class DeviceMetadata{String name="",description="",deviceType="",location="",softwareVersion="",platform="",status="unavailable";}
private static final class CachedMetadata{final long createdAt;final DeviceMetadata value;CachedMetadata(long time,DeviceMetadata metadata){createdAt=time;value=metadata;}}
private static String json(String value){if(value==null)return"";StringBuilder result=new StringBuilder();for(int i=0;i<value.length();i++){char c=value.charAt(i);switch(c){case'\\':result.append("\\\\");break;case'\"':result.append("\\\"");break;case'\n':result.append("\\n");break;case'\r':result.append("\\r");break;case'\t':result.append("\\t");break;default:if(c<32)result.append(String.format("\\u%04x",(int)c));else result.append(c);}}return result.toString();}
private static String clean(String value){if(value==null)return"";value=value.trim();return"null".equalsIgnoreCase(value)||"undefined".equalsIgnoreCase(value)?"":value;}
private static String value(Map<String,String> values,String name){String result=clean(values.get(name));if(result.length()==0)result=clean(values.get(name+".0"));return result;}
private static String softwareVersion(String description){Matcher named=VERSION_LABEL.matcher(description==null?"":description);if(named.find())return clean(named.group(1));Matcher parenthesized=PAREN_VERSION.matcher(description==null?"":description);return parenthesized.find()?clean(parenthesized.group(1)):"";}
private static String platform(String description,String model){String value=(clean(description)+" "+clean(model)).toLowerCase(Locale.ENGLISH);if(value.contains("fabricengine")||value.contains("fabric engine")||value.contains("voss")||value.matches(".*\\bvsp\\b.*"))return"FabricEngine";if(value.contains("switchengine")||value.contains("switch engine")||value.contains("extremexos")||value.matches(".*\\bexos\\b.*"))return"SwitchEngine";return"Other";}
private static void openSnmp(SnmpUtilV3 snmp,String ip,Properties credential)throws Exception{String version=credential.getProperty("version","v2c");if("v3".equals(version)){String level=credential.getProperty("securityLevel","authPriv"),authName=credential.getProperty("authProtocol","SHA"),privName=credential.getProperty("privProtocol","AES");int auth="MD5".equals(authName)?1:"SHA".equals(authName)?2:0,priv="DES".equals(privName)?1:"AES".equals(privName)?2:"3DES".equals(privName)?3:0;if("noAuthNoPriv".equals(level)){auth=0;priv=0;}else if("authNoPriv".equals(level))priv=0;snmp.openSessionV3(ip,credential.getProperty("username",""),auth,credential.getProperty("v3AuthPassword",""),priv,credential.getProperty("v3PrivPassword",""),credential.getProperty("context",""));}else{snmp.setSnmpVersion("v1".equals(version)?0:1);snmp.openSession(ip,credential.getProperty("roCommunity",""),credential.getProperty("rwCommunity",""));}}
private static DeviceMetadata loadMetadata(String ip){CachedMetadata cached=METADATA_CACHE.get(ip);long now=System.currentTimeMillis();if(cached!=null&&now-cached.createdAt<METADATA_TTL_MS)return cached.value;DeviceMetadata metadata=new DeviceMetadata();SnmpUtilV3 snmp=new SnmpUtilV3();try{openSnmp(snmp,ip,CredentialVault.getSnmpForDevice(ip));String[] variables={"sysName.0","sysDescr.0","rcChasModelName.0","sysLocation.0"},names={"sysName","sysDescr","rcChasModelName","sysLocation"},result;try{result=snmp.getAttribute(variables,false);}catch(IllegalArgumentException unsupported){result=new String[variables.length];for(int i=0;i<variables.length;i++)try{result[i]=snmp.getAttribute(new String[]{variables[i]},false)[0];}catch(Exception ignored){result[i]="";}}Map<String,String> values=new HashMap<String,String>();for(int i=0;i<result.length&&i<names.length;i++)values.put(names[i],result[i]);metadata.name=value(values,"sysName");metadata.description=value(values,"sysDescr");String model=value(values,"rcChasModelName");metadata.deviceType=model.length()>0?model:metadata.description;metadata.location=value(values,"sysLocation");metadata.softwareVersion=softwareVersion(metadata.description);metadata.platform=platform(metadata.description,model);metadata.status="available";}catch(Exception ignored){}finally{try{snmp.closeSession();}catch(Exception ignored){}}METADATA_CACHE.put(ip,new CachedMetadata(now,metadata));return metadata;}
private static String deviceJson(String ip,Properties ssh,DeviceMetadata metadata){StringBuilder result=new StringBuilder("{");result.append("\"id\":\"device-").append(json(ip)).append("\",");result.append("\"name\":\"").append(json(metadata.name.length()>0?metadata.name:ip)).append("\",");result.append("\"host\":\"").append(json(ip)).append("\",");result.append("\"protocol\":\"ssh\",");result.append("\"port\":").append(Math.max(1,Integer.parseInt(ssh.getProperty("port","22")))).append(',');result.append("\"deviceType\":\"").append(json(metadata.deviceType)).append("\",");result.append("\"platform\":\"").append(json(metadata.platform)).append("\",");result.append("\"sysLocation\":\"").append(json(metadata.location)).append("\",");result.append("\"softwareVersion\":\"").append(json(metadata.softwareVersion)).append("\",");result.append("\"sysDescription\":\"").append(json(metadata.description)).append("\",");result.append("\"metadataStatus\":\"").append(metadata.status).append("\",");result.append("\"credential\":{");result.append("\"username\":\"").append(json(ssh.getProperty("username",""))).append("\",");result.append("\"password\":\"").append(json(ssh.getProperty("sshPassword",""))).append("\",");result.append("\"privateKey\":\"").append(json(ssh.getProperty("sshPrivateKey",""))).append("\",");result.append("\"keyPassphrase\":\"").append(json(ssh.getProperty("sshKeyPassphrase",""))).append("\"}}");return result.toString();}
%><%
response.setHeader("Cache-Control","no-store, max-age=0");response.setHeader("Pragma","no-cache");response.setHeader("X-Robots-Tag","noindex, nofollow");response.setHeader("Vary","Authorization");response.setCharacterEncoding("UTF-8");
if(!"GET".equals(request.getMethod())&&!"HEAD".equals(request.getMethod())){response.setStatus(405);response.setHeader("Allow","GET, HEAD");out.print("{\"error\":\"method_not_allowed\"}");return;}
if(!FabricNavigatorApiToken.authenticate(request)){response.setStatus(401);response.setHeader("WWW-Authenticate","Bearer realm=\"FabricNavigator API\"");out.print("{\"error\":\"invalid_token\"}");return;}
List<String> ips=new ArrayList<String>(CredentialVault.listAssignedDevices());Collections.sort(ips);final Map<String,Properties> credentials=new LinkedHashMap<String,Properties>();for(String ip:ips)try{String id=CredentialVault.getDeviceCredentialId(ip,CredentialVault.TYPE_SSH);if(id==null||id.length()==0)continue;Properties ssh=CredentialVault.getCredential(id);if(CredentialVault.TYPE_SSH.equals(ssh.getProperty("type"))&&"true".equalsIgnoreCase(ssh.getProperty("enabled","true")))credentials.put(ip,ssh);}catch(Exception ignored){}
final Map<String,DeviceMetadata> metadata=new ConcurrentHashMap<String,DeviceMetadata>();int workers=Math.max(1,Math.min(8,credentials.size()));ExecutorService executor=Executors.newFixedThreadPool(workers,new ThreadFactory(){public Thread newThread(Runnable runnable){Thread thread=new Thread(runnable,"fn-acli-api-snmp");thread.setDaemon(true);return thread;}});List<Callable<Void>> tasks=new ArrayList<Callable<Void>>();for(final String ip:credentials.keySet())tasks.add(new Callable<Void>(){public Void call(){metadata.put(ip,loadMetadata(ip));return null;}});try{executor.invokeAll(tasks,15,TimeUnit.SECONDS);}finally{executor.shutdownNow();}
if("HEAD".equals(request.getMethod()))return;StringBuilder payload=new StringBuilder("{\"apiVersion\":1,\"fabricNavigatorVersion\":\"").append(json(System.getenv("FABRICNAVIGATOR_VERSION"))).append("\",\"generatedAt\":\"").append(Instant.now().toString()).append("\",\"devices\":[");int count=0;for(Map.Entry<String,Properties> item:credentials.entrySet()){if(count++>0)payload.append(',');DeviceMetadata current=metadata.get(item.getKey());if(current==null)current=new DeviceMetadata();payload.append(deviceJson(item.getKey(),item.getValue(),current));}payload.append("]}");out.print(payload.toString());try{AuditLog.log("api:"+FabricNavigatorApiToken.label(),"FABRICNAVIGATOR_API_READ","exported "+count+" SSH session"+(count==1?"":"s"),request.getRemoteAddr());}catch(Exception ignored){}
%>
