package com.fabricnavigator.firmware;

import com.fabricnavigator.backup.ConfigurationBackupScheduler;
import com.fabricnavigator.features.FeatureFlags;
import com.fabricnavigator.security.AuditLog;
import com.fabricnavigator.security.CredentialVault;
import com.fabricnavigator.security.KnownHostsManager;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public final class FirmwareDeploymentManager {
    private static final ExecutorService EXECUTOR=Executors.newSingleThreadExecutor(new ThreadFactory(){public Thread newThread(Runnable r){Thread t=new Thread(r,"fabricnavigator-firmware-deployment");t.setDaemon(true);return t;}});
    private static final Object LOCK=new Object();private static volatile Status status=new Status();
    private FirmwareDeploymentManager(){}
    public static final class Status {public String id="",state="idle",message="",currentDevice="";public int completed,total,failed;public List<String> results=new ArrayList<String>();}
    public static Status status(){Status source=status,copy=new Status();copy.id=source.id;copy.state=source.state;copy.message=source.message;copy.currentDevice=source.currentDevice;copy.completed=source.completed;copy.total=source.total;copy.failed=source.failed;copy.results=new ArrayList<String>(source.results);return copy;}
    public static boolean start(final String packageId,Collection<String> requested,final boolean reboot,final String actor,final String remote) throws Exception {
        FeatureFlags.requireFirmwareLifecycle();final FirmwarePackageStore.Package firmware=FirmwarePackageStore.get(packageId);final List<String> devices=new ArrayList<String>();Set<String> known=CredentialVault.listAssignedDevices();for(String device:requested){validateDevice(device);if(!known.contains(device))throw new IllegalArgumentException("Unknown device: "+device);if(!devices.contains(device))devices.add(device);}if(devices.isEmpty()||devices.size()>100)throw new IllegalArgumentException("Select between 1 and 100 devices");
        synchronized(LOCK){if("running".equals(status.state))return false;status=new Status();status.id=UUID.randomUUID().toString();status.state="running";status.total=devices.size();status.message="Firmware deployment queued";}
        EXECUTOR.submit(new Runnable(){public void run(){runDeployment(firmware,devices,reboot,actor,remote);}});return true;
    }
    private static void runDeployment(FirmwarePackageStore.Package firmware,List<String> devices,boolean reboot,String actor,String remote){for(String device:devices){status.currentDevice=device;status.message="Validating SSH and creating safety backup";try{Properties credential=CredentialVault.getSshForDevice(device);int port=parseInt(credential.getProperty("port"),22);String approved=KnownHostsManager.approvedFingerprint(device,port);if(approved==null||approved.length()==0)throw new SecurityException("SSH host key is not approved");KnownHostsManager.Pending scanned=KnownHostsManager.scan(device,port);if(!approved.equals(scanned.fingerprint))throw new SecurityException("SSH host key changed");if(FeatureFlags.configurationBackupEnabled())ConfigurationBackupScheduler.capture(device,actor,"pre-firmware-upgrade",remote);status.message="Uploading and staging firmware on "+device;ProcessResult result=runHelper(device,credential,firmware,reboot);if(result.code!=0)throw new IOException(result.error);status.results.add(device+" · staged"+(reboot?" · reboot requested":" · reboot not requested"));AuditLog.log(actor,"FIRMWARE_DEPLOYED",device+" · package="+firmware.id+" · version="+firmware.version+" · platform="+firmware.platform+" · sha256="+firmware.sha256+" · reboot="+reboot,remote);}catch(Exception ex){status.failed++;status.results.add(device+" · FAILED · "+safe(ex));try{AuditLog.log(actor,"FAILED_FIRMWARE_DEPLOYMENT",device+" · package="+firmware.id+" · "+safe(ex),remote);}catch(Exception ignored){}}status.completed++;}status.currentDevice="";status.state=status.failed>0?"warning":"success";status.message=status.failed>0?status.completed+" completed · "+status.failed+" failed":"Firmware deployment completed";}
    private static ProcessResult runHelper(String device,Properties c,FirmwarePackageStore.Package firmware,boolean reboot)throws Exception {Process process=new ProcessBuilder("/usr/bin/perl","/opt/fabricnavigator/firmware-deploy.pl").start();BufferedWriter input=new BufferedWriter(new OutputStreamWriter(process.getOutputStream(),StandardCharsets.UTF_8));for(String value:new String[]{device,c.getProperty("username",""),c.getProperty("sshPassword",""),c.getProperty("sshPrivateKey",""),c.getProperty("sshKeyPassphrase","")}){input.write(Base64.getEncoder().encodeToString(value.getBytes(StandardCharsets.UTF_8)));input.newLine();}input.write(c.getProperty("port","22"));input.newLine();for(String value:new String[]{firmware.platform,firmware.file.toString(),firmware.fileName,firmware.activation,Boolean.toString(reboot)}){input.write(Base64.getEncoder().encodeToString(value.getBytes(StandardCharsets.UTF_8)));input.newLine();}input.close();Collector out=new Collector(process.getInputStream()),err=new Collector(process.getErrorStream());Thread a=new Thread(out),b=new Thread(err);a.start();b.start();if(!process.waitFor(45,TimeUnit.MINUTES)){process.destroyForcibly();throw new IOException("Firmware operation timed out");}a.join();b.join();return new ProcessResult(process.exitValue(),err.value().length()>0?err.value():out.value());}
    private static class ProcessResult {int code;String error;ProcessResult(int code,String error){this.code=code;this.error=error;}}
    private static class Collector implements Runnable {InputStream input;ByteArrayOutputStream output=new ByteArrayOutputStream();Collector(InputStream input){this.input=input;}public void run(){try{byte[] b=new byte[8192];int n;while((n=input.read(b))>=0){if(output.size()<1024*1024)output.write(b,0,Math.min(n,1024*1024-output.size()));}}catch(Exception ignored){}}String value(){return new String(output.toByteArray(),StandardCharsets.UTF_8).trim();}}
    private static int parseInt(String value,int fallback){try{return Integer.parseInt(value);}catch(Exception ex){return fallback;}}
    private static void validateDevice(String value){if(value==null||!value.matches("(?:[0-9]{1,3}\\.){3}[0-9]{1,3}"))throw new IllegalArgumentException("Invalid device IP");for(String item:value.split("\\."))if(Integer.parseInt(item)>255)throw new IllegalArgumentException("Invalid device IP");}
    private static String safe(Exception ex){String value=ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage();return value.replace('\r',' ').replace('\n',' ').substring(0,Math.min(500,value.length()));}
}
